OnlineStoreMVC/Controllers/CVController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using OnlineStoreMVC.Models;
using System.Globalization;
using System.Collections.Generic;
using PagedList;

namespace OnlineStoreMVC.Controllers
{
    public class CVController : Controller
    {

        [NonAction]
        public bool HasCv(string userName)
        {
            bool hasCv;
            using (var db = new EntityDbContext())
            {
                hasCv = db.Cvs.Any(x => x.UserName == User.Identity.Name);
            }


            return hasCv;
        }

        [Authorize]
        public ActionResult AddYourCV()
        {
            if (HasCv(User.Identity.Name))
                return RedirectToAction("EditCv");
            return View();
        }

        [HttpPost]
        public ActionResult AddYourCV(CvModel model)
        {
            if (model.Skills.Last().SkillName == null || model.Skills.Last().SkillDescription==null)
            {
               

                return Content("Error Nie podano umiejętności");

            }
            if (model.Hobby == null)
            {
                return Content("Error Nie podano swoich hobby");

            }
            if (model.Profession == null)
            {
                return Content("Error Nie podano swojego zawodu");
            }
            if (model.Experiences.Count == 1 &&
                (model.Experiences.Last().JobStartTime != null ||  model.Experiences.Last().JobEndTime !=null))
            {

                foreach (var exp in model.Experiences)
                {
                    DateTime dataFrom = new DateTime();
                    DateTime dataTo = new DateTime();

                    DateTime.TryParse(exp.JobStartTime+" 00:00:00",new CultureInfo("pl-PL"),DateTimeStyles.AssumeUniversal, out dataFrom);
                    DateTime.TryParse(exp.JobEndTime + " 00:00:00", new CultureInfo("pl-PL"), DateTimeStyles.AssumeUniversal, out dataTo);


                    if (dataFrom.ToShortDateString() == "0001-01-01" || dataTo.ToShortDateString() == "0001-01-01") { return Content("Error Podano niepoprawne daty");}
                    
                }

                
            }
            if (model.Educations.Count == 1 &&
               (model.Educations.Last().StartDate != null || model.Educations.Last().EndDate != null))
            {

                foreach (var edu in model.Educations)
                {
                    DateTime dataFrom = new DateTime();
                    DateTime dataTo = new DateTime();

                    DateTime.TryParse(edu.StartDate + " 00:00:00", new CultureInfo("pl-PL"), DateTimeStyles.AssumeUniversal, out dataFrom);
                    DateTime.TryParse(edu.EndDate + " 00:00:00", new CultureInfo("pl-PL"), DateTimeStyles.AssumeUniversal, out dataTo);


                    if (dataFrom.ToShortDateString() == "0001-01-01" || dataTo.ToShortDateString() == "0001-01-01") { return Content("Error Podano niepoprawne daty"); }

                }


            }


            using (EntityDbContext db = new EntityDbContext())
            {

                foreach (var item in model.Experiences)
                {
                    if (item.JobStartTime != null || item.JobEndTime != null)
                    {
                        db.Experiences.Add(item);

                       
                    }
                    
                }

                foreach (var item in model.Skills)
                {
                    db.Skills.Add(item);

                   
                }

                foreach (var item in model.Certificates)
                {
                    if (item.CertificateDesc != null || item.CertificateName != null)
                    {
                        db.Certificates.Add(item);

                     
                    }
                    
                }
                foreach (var item in model.Languages)
                {
                    if (item.LanguageName != null )
                    {
                        db.Languages.Add(item);

                        
                    }
                }
                foreach (var item in model.Educations)
                {
                    if (item.SchollName != null)
                    {
                        db.Educations.Add(item);


                    }
                }


                
                db.Hobbies.Add(model.Hobby);
                db.Professions.Add(model.Profession);
                db.Cvs.Add(new CV() {UserName = User.Identity.Name, hasCV = true});


                try
                {
                    db.SaveChanges();

                }

                catch (Exception)
                {   
                    return Content("Error Błąd walidacji danych. Upewnij się czy wpisane teksty nie są zbyt długie.") ;
                }
                    
                
            }

            return Content("Dane zostały zapisane poprawnie");
        }

        [Authorize]
        public ActionResult EditCv()
        {
            if (!HasCv(User.Identity.Name))
                return RedirectToAction("AddYourCV");

            var db = new EntityDbContext();

            var userName = User.Identity.Name;

            //First Model
            var exp = db.Experiences.Where(x => x.UserName == userName).ToList();
            var hob = db.Hobbies.FirstOrDefault(x => x.UserName == userName) ?? new Hobby() { HobbyDesc = " " };
            var cert = db.Certificates.Where(x => x.UserName == userName).ToList();
            var lang = db.Languages.Where(x => x.UserName == userName).ToList();
            var skill = db.Skills.Where(x => x.UserName == userName).ToList();
            var prof = db.Professions.FirstOrDefault(x => x.UserName == userName) ?? new Profession() { ProfessionName = " " };
            var edus = db.Educations.Where(x => x.UserName == userName).ToList();
         
                      

            CvModel cvModel = new CvModel()
            {
                Experiences =  exp,
                Certificates = cert,
                Languages=lang,
                Skills = skill,
                Hobby = hob,
                Profession = prof,
                Educations = edus

            };
            //Second Model
            var user = db.Users.FirstOrDefault(x => x.Nickname == userName);

            db.Dispose();

            if (user == null)
            {
                ViewBag.UserIsEmpty = true;
                return View();
            }
            
            var tuple = new Tuple<CvModel,UserViewModel>(cvModel,user);

            return View(tuple);
        }

        [HttpPost]
        public ActionResult DeleteCv(string userName)
        {
            if (userName != null)
            {
                using (EntityDbContext db = new EntityDbContext())
                {
                    db.Database.ExecuteSqlCommand("Delete from Experiences where UserName='" + userName+"'");
                    db.Database.ExecuteSqlCommand("Delete from Hobbies where UserName='" + userName+"'");
                    db.Database.ExecuteSqlCommand("Delete from Certificates where UserName='" + userName+"'");
                    db.Database.ExecuteSqlCommand("Delete from Languages where UserName='" + userName+"'");
                    db.Database.ExecuteSqlCommand("Delete from Skills where UserName='" + userName+"'");
                    db.Database.ExecuteSqlCommand("Delete from Cvs where UserName='" + userName+"'");
                    db.Database.ExecuteSqlCommand("Delete from Professions where UserName='" + userName + "'");
                    db.Database.ExecuteSqlCommand("Delete from Educations where UserName='" + userName + "'");
                    db.SaveChanges();

                }

                return RedirectToAction("AddYourCV");
            }


            return RedirectToAction("EditCv");

        }

        public ActionResult _Experiences()
        {
          
            return PartialView();

        }



        [HttpPost]
        public ActionResult AddExperience(CvModel model)
        {

            return PartialView("_Experiences");
        }
            


        [Authorize]
        public ActionResult _Skills()
        {
            return PartialView();
        }

        [Authorize]
        public ActionResult _Certifications()
        {

            return PartialView();
        }
        [Authorize]
        public ActionResult _Languages()
        {

            return PartialView();
        }

       
        [Authorize]
        public ActionResult _Hobby()
        {
            return PartialView();
        }

        [Authorize]
        public ActionResult _Profession()
        {
            return PartialView();
        }

        [Authorize]
        public ActionResult _Education()
        {
            return PartialView();
        }

        [Authorize]
        public ActionResult AddBranch(FormCollection collection)
        {
            EntityDbContext db = new EntityDbContext();
            var user = db.Users.First(x => x.Nickname == User.Identity.Name);
            user.Branch = collection["Branch"];
            //user.Branch = "Admin";
            db.SaveChanges();
            return RedirectToAction("EditCv");
        }

        //Branch specified as ID to use existing routing (CV/Browse/Informatyka)
        public ActionResult Browse(string ID, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            EntityDbContext db = new EntityDbContext();
            List<UserViewModel> users;
            List<UserViewModel> result = new List<UserViewModel>();
            //show all branches when branch is not specified
            if (ID == null)
            {
                users = db.Users.OrderBy(x => x.UserID).ToList();
            }
            else
            {
                users = db.Users.Where(x => x.Branch == ID).OrderBy(x => x.UserID).ToList();

OnlineStoreMVC/Views/Shared/404NotFound.cshtml
@{
    Layout = null;
    ViewBag.Title = "Error";
}

<style>
    #errorContent {
        height: 100%;
        width: 100%;
        text-align: center;
        background-color: #5a76b9;
    }  
    #errorLink {
        color: white;
        text-align: center;
        font-size: 40px;
        text-decoration: none;
    }
</style>

<div style="width: 100%; background-color: #5a76b9; text-align: center;">
   @Html.ActionLink("Wróć na stronę główną","Index","Home",null,new{@id="errorLink"})
</div>
<div id="errorContent">
    
    <img src="@Url.Content("~/Content/404notFound.jpg")" alt="Error image" class="img-responsive"/>
</div>

OnlineStoreMVC/Views/Shared/_BackendMenuPartial.cshtml
@using (Html.BeginForm("Search", "Search", FormMethod.Post, new { @class = "navbar-form navbar-left", role = "search",@style="padding-top:10px;" }))
{

    
    <div class="form-group">
        @Html.TextBox("searchquery", "", new { Name="query", @id = "query", @class = "form-control input-sm", placeholder = "Znajdź na stronie" })
        @Html.Hidden("fromcontroller", @ViewContext.RouteData.Values["controller"], new { @id = "fromcontroller" })
       
    </div>
    <button type="submit" class="btn btn-default" style="padding: 4px 12px">Szukaj</button>
     

}

OnlineStoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.bootstrap.js"></script>
    <!-- Bootstrap -->
    <link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <style>
        * {
            margin: 0;
        }

        html, body {
            height: 100%;
        }

        .wrapper {
            min-height: 100%;
            height: auto !important;
            height: 100%;
            margin: 0 auto -4em;
        }

        .footer, .push {
            height: 6em;
        }

        #Main {
            background-color: white;
            background-image: none;
        }
        #NoVideo {
            display: none;
        }

    </style>

    @Styles.Render("~/Content/Site.css")

    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/navbar.css")
    @Styles.Render("~/Content/Slider.css")
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/
    html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/
    respond.min.js"></script>
    <![endif]-->
</head>
<body id="@(ViewData["PageID"]??"")">
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">

                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Northwind Traders", "Index", "Home", null, new { @class = "navbar-brand", @style = "padding-top:27px;" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li style="height: 70px; padding-top: 10px;">@Html.ActionLink("Strona główna", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li style="height: 70px; padding-top: 10px;">@Html.ActionLink("Kandydaci", "Browse", "CV")</li>
                    }
                    <li style="height: 70px; padding-top: 10px;">@Html.ActionLink("Kontakt", "Index", "Home")</li>



                </ul>
                @Html.Partial("_BackendMenuPartial")
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div id="@(ViewData["Video"]??"NoVideo")">

        @{ Html.RenderAction("_Video", "Home");}
        <script>

            $(document).ready(function () {

                $("body").addClass("anotherBody");
                $(".player").mb_YTPlayer();

            });
        </script>
    </div>




    <div class="container body-content wrapper">
        @RenderBody()
        <br />
        <hr />
    </div>

    <div class="footer" style="text-align:center; background-color: #a9a9a9; width: 100%; margin-bottom: 0px; border-radius: 5px; font-size: 18px; color: white; vertical-align: central; ">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </div>


    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)

</body>

</html>